# Generated by Django 4.0.4 on 2022-06-09 11:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='views',
        ),
        migrations.AddField(
            model_name='song',
            name='viewers',
            field=models.ManyToManyField(blank=True, related_name='viewers', to=settings.AUTH_USER_MODEL),
        ),
    ]
