# Generated by Django 4.0.4 on 2022-06-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_remove_song_views_song_viewers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='viewers',
        ),
        migrations.AddField(
            model_name='song',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
