# Generated by Django 4.0.4 on 2022-06-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_remove_song_viewers_song_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='lyric',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='song',
            name='photo',
            field=models.ImageField(default=None, null=True, upload_to='images'),
        ),
    ]
