# Generated by Django 4.0.4 on 2022-06-10 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_alter_song_lyric_alter_song_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='photo',
            field=models.ImageField(blank=True, default=None, upload_to='images'),
        ),
    ]
