# Generated by Django 4.0.4 on 2022-06-10 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_alter_song_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='lyric',
        ),
    ]
